#!/bin/bash/
cd $PYSU_DIR/pyGalaxy/trunk/bin_stack

# Stacking LF spectra
# DATA
# stacks after the luminosity function from $LFMODELS_DIR
python stack_spectra_all

# MODEL
# copy the stacks of interest to $SPECTRASTACKS_DIR/data/
cp $VVDS_DIR/products/spectraStacks/O2_3728/*.fits  $SPECTRASTACKS_DIR/data/O2_3728/
cp $VVDS_DIR/products/spectraStacks/O3_5007/*.fits  $SPECTRASTACKS_DIR/data/O3_5007/
cp $DEEP2_DIR/products/spectraStacks/H1_4862/*.fits  $SPECTRASTACKS_DIR/data/H1_4862/
cp $DEEP2_DIR/products/spectraStacks/O2_3728/*.fits  $SPECTRASTACKS_DIR/data/O2_3728/
cp $DEEP2_DIR/products/spectraStacks/O3_5007/*.fits  $SPECTRASTACKS_DIR/data/O3_5007/
# remove the ones that are not from a complete LF TBD
#rm  $SPECTRASTACKS_DIR/data/O2_3728/O2_3728-DEEP2R24.2-z0.778*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-DEEP2R24.2-z0.451*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-DEEP2R24.2-z0.767*
#rm  $SPECTRASTACKS_DIR/data/H1_4862/H1_4862-DEEP2R24.2-z0.775*
#rm  $SPECTRASTACKS_DIR/data/O2_3728/O2_3728-VVDSDEEPI24-z0.69*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-VVDSDEEPI24-z0.294*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-VVDSDEEPI24-z0.606*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-VVDSDEEPI24-z0.674*
#rm  $SPECTRASTACKS_DIR/data/O3_5007/O3_5007-VVDSDEEPI24-z0.741*

cd $SPECTRASTACKS_DIR/scripts/
python presentationPlot.py
#produces the first two figures of the paper presenting the data.

# fit firefly stellar population continuum models
cd $PYSU_DIR/pySPM/trunk/bin
screen python setup_run_for_stacks_VVDSDEEP
screen python setup_run_for_stacks_DEEP2
# writes to to $SPECTRASTACKS_DIR/fits/

cd $PYSU_DIR/pyGalaxy/trunk/bin_stack
# relink things correclty :
screen python model_stacked_spectra_DEEP2
screen python model_stacked_spectra_VVDS
# writes to to $SPECTRASTACKS_DIR/model/
# model files hdus :
# hdu[0] : header : contains LF information (no data)
# hdu[1] : stack
# hdu[2] : firefly best fit. header contains output parameters
# hdu[3] : emission line spectrum = stack - firefly continuum model
# hdu[4] : emissiion line fit to the emission line spectrum
# hdu[5] : emissiion line fit to the stack
# hdu 
# generate data sanity check oriented plots 
python plot_firefly_model

# concatenates results
python create_master_table
# output in  join(os.environ['SPECTRASTACKS_DIR'], "results", "table_lineSpecFit_v0.fits")
# computes balmer decrements, line ratios, metallicities ...
python process_master_table
#output in join(os.environ['SPECTRASTACKS_DIR'], "results", "table_lineSpecFit_v0.VA.fits")

# RUN CODE FROM HERE ON :
# generate science oriented plots 
python plot_results_spectraStacks


./compute_intrinsic_LFs
