#! /usr/bin/env python

from os.path import join
import os
import glob
import numpy as n

dataList = n.array(glob.glob(join(os.environ['DATA_DIR'],"ELG-composite", "stacks", "data", "*.asc")))
dataList.sort()
stackList = n.array([ spec[:-4]+".stack" for spec in dataList ])

executable = join(os.environ['PYSU_DIR'], "spm", "bin", "stellarpop_stacks_EBOSS")
el = stackList[0]
command = "python  " + executable + " " + el
os.system( command )
for ii, el in enumerate(stackList):
	if os.path.isfile(el) :
		print ii
		command = "python  " + executable + " " + el
		os.system( command )
