#! /usr/bin/env python

from os.path import join
import os
import glob
import numpy as n

stackList = n.array(glob.glob(join(os.environ['EBOSS_TARGET'],"elg", "tests", "stacks", "data", "*.stack")))

executable = join(os.environ['PYSU_DIR'], "spm", "bin", "stellarpop_stacks_EBOSS")

for ii, el in enumerate(stackList):
	command = "python  " + executable + " " + el
	os.system( command )
