#! /usr/bin/env python

"""
This script produces the stacks for emission line luminosity limited samples.
"""
import sys
import os 
from os.path import join
import glob
import numpy as n
import SpectraStackingEBOSS as sse

dataList = n.array(glob.glob(join(os.environ['EBOSS_TARGET'],"elg", "tests", "stacks", "lists_2_stack", "*.asc")))

for specList in dataList:
	print specList
	outfile = join(os.environ['EBOSS_TARGET'],"elg", "tests", "stacks", os.path.basename(specList)[:-4]+".stack")
	stack=sse.SpectraStackingEBOSS(specList, outfile)
	stack.stackSpectraSDSS()
		
