#! /usr/bin/env python

"""
This script produces the stacks for emission line luminosity limited samples.
"""
import sys
import os 
from os.path import join
import glob
import numpy as n
import astropy.io.fits as fits
import SpectraStackingEBOSS as sse

# create all input files :
path_2_cat = join(os.environ['HOME'],"SDSS/lss/catalogs/3", "eBOSS_ELG_clustering_ALL_v3.dat.fits")

cat = fits.open(path_2_cat)

selection = 
DATA = n.transpose([])
# self.plates, self.mjds, self.fiberids, self.redshifts
path_2_input = join(os.environ['HOME'],"SDSS/lss/catalogs/3", "XXX.asc")
n.savetxt(path_2_input, DATA)

## create all stacks
#dataList = n.array(glob.glob(join(os.environ['HOME'],"SDSS/lss/catalogs/3", "*.asc")))

#for specList in dataList:
	#print( specList )
	#outfile = join(os.environ['HOME'],"SDSS", "stacks", os.path.basename(specList)[:-4]+".stack")
	#stack=sse.SpectraStackingEBOSS(specList, outfile)
	#print(outfile)
	#stack.stackSpectra()
	#outfile = join(os.environ['HOME'],"SDSS", "stacks", os.path.basename(specList)[:-4]+".UVstack")
	#stack=sse.SpectraStackingEBOSS(specList, outfile)
	#print(outfile)
	#stackSpectra_UVnormed()
		
