#! /usr/bin/env python

from InterpretStacksAndLFs import *

lf_files=n.hstack(( n.array(glob.glob(join(data_dir,"DEEP2", "products", "emissionLineLuminosityFunctions", "??_????", "*-z?.???.fits"))), 
n.array(glob.glob(join(data_dir,, "VVDS", "products", "emissionLineLuminosityFunctions", "??_????", "*-z?.???.fits"))) )

lf_files.sort()

for file in lf_files :
	print file
	mm = IntrinsicStacksAndLFs( file )
	mm.apply_correction()
