#! /usr/bin/env python

from ModelSpectraStacks import *
import glob
from os.path import join
import os

stack_files=n.array(glob.glob( join( os.environ['SPECTRASTACKS_DIR'], "data", "??_????", "*VVDSDEEP*.fits" ) ) )
stack_files.sort()

#print stack_files

for file in stack_files[:2]:
	print( file )
	mm=ModelSpectraStacks(file,mode="MILES")
	#mm.plot_fit()
	mm.fit_lines_to_fullSpectrum()
	mm.fit_lines_to_lineSpectrum()
	#mm.compute_derived_quantities()
	mm.save_spectrum()
	#mm.plot_spectrum()

