#! /usr/bin/env python

from IntrinsicStacksAndLFs import *

lf_files =n.array(glob.glob(join(os.environ['VVDS_DIR'], "products", "emissionLineLuminosityFunctions", "??_????", "*intrinsic*")))
lf_files =n.array(glob.glob(join(os.environ['DEEP2_DIR'], "products", "emissionLineLuminosityFunctions", "??_????", "*intrinsic*")))
print lf_files
lf_files.sort()

for file in lf_files :
	print file
	mm = IntrinsicStacksAndLFs( file )
	mm.apply_correction()
