#! /usr/bin/env python

import os
from os.path import join
import sys
import numpy as n
import sys
import matplotlib
#matplotlib.use('pdf')
import matplotlib.pyplot as p
import astropy.io.fits as fits 

from scipy.stats import scoreatpercentile as sap
from scipy.interpolate import interp1d
import glob

gaussianLine=lambda aa,sigma,F0,a0,continu : continu + F0*(n.e**( -(aa-a0)**2. / (2.*sigma**2.)))/ (abs(sigma)*(2.*n.pi)**0.5)
gaussianLineNC=lambda aa,sigma,F0,a0 : F0*(n.e**(-(aa-a0)**2./ (2.*sigma**2.) ))/(abs(sigma)*(2.*n.pi)**0.5)

stL=n.array(glob.glob( join( os.environ['SPECTRASTACKS_DIR'], "model", "??_????", "*.model" ) ) )

#print stL

def plotStack( modeledStackFile ):
	baseN = os.path.basename(modeledStackFile)
	outputFigureNameRoot = join( os.environ['SPECTRASTACKS_DIR'], "plots", "models", baseN)
	hdus = fits.open(modeledStackFile )
	Nspecs = float(baseN.split('_')[4])
	element = baseN.split('-')[0]
	lineDict = {'O2_3728' : r'$[O^{3728}_{II}]$', 'O3_5007' : r'$[O^{5007}_{III}]$', 'H1_4862' : r'$H^{4861}_{\beta}$', 'H1_4341' : r'$H^{4341}_{\gamma}$', 'H1_4102' : r'$H^{4102}_{\delta}$', 'H1_6564': r'$H^{6564}_{\alpha}$'}
	line = lineDict[element]
	#print  hdus[0].header
	redshift = float(hdus[0].header['LF_FILE_name'].split('-')[-1][1:])
	Lmean = n.round( n.log10(hdus[0].header['L_mean']) ,2)
	Lmax  = n.round( n.log10(hdus[0].header['L_max'])  ,2)
	Lmin  = n.round( n.log10(hdus[0].header['L_min'])  ,2)
	selection = (hdus[1].data['NspectraPerPixel']>0.8*Nspecs) &(hdus[1].data['meanWeightedStack']> hdus[1].data['jackknifStackErrors'])
	wl = hdus[1].data['wavelength'][selection]
	flObs = hdus[1].data['meanWeightedStack'][selection]
	flObsErr = hdus[1].data['jackknifStackErrors'][selection]
	wl_fir = hdus[2].data['wavelength']
	fl_fir = hdus[2].data['firefly_model'] * 1e-17
	Ms = n.round(hdus[2].header['stellar_mass_mean'] , 2)
	age = n.round( hdus[2].header['age_lightW_mean'] , 2)
	metal = n.round( hdus[2].header['metallicity_lightW_mean'] , 3)
	wl_ls = hdus[3].data['wavelength']
	flObs_ls = hdus[3].data['flux']
	flObsErr_ls = hdus[3].data['fluxErr']
	# hdus[2].header['stellar_mass']

	p.figure(1,(12,4))
	p.axes([0.1,0.2,0.85,0.75])
	p.errorbar(wl,flObs,yerr = flObsErr,label= "z="+str(redshift)+", "+str(Lmin) +"< log(L"+line+")<"+ str(Lmax), marker = 'x', c='b', ls='None')
	p.plot(wl_fir, fl_fir,'k',lw=2,label = 'log(age)='+ str(age)+ ', log(M*)='+ str(Ms)+ ', log(Z)='+ str(metal))
	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	p.yscale('log')
	p.legend(fontsize=12) 
	p.savefig( outputFigureNameRoot + "-all.png")
	p.clf()

	p.figure(1,(12,4))
	p.axes([0.1,0.2,0.85,0.75])
	p.errorbar(wl,flObs,yerr = flObsErr,label="z="+str(redshift)+", "+ str(Lmin) +"< log(L"+line+")<"+ str(Lmax), marker = 'x', c='b', ls='None')
	p.plot(wl_fir, fl_fir,'k',lw=2,label =  'log(age)='+ str(age)+ ', log(M*)='+ str(Ms)+ ', log(Z)='+ str(metal))
	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	p.yscale('log')
	p.ylim(( n.min(fl_fir)*0.8, n.max(fl_fir)*1.2 ))
	p.legend(fontsize=12, loc=4) 
	p.savefig( outputFigureNameRoot + "-cont.png")
	p.clf()

	p.figure(1,(12,4))
	p.axes([0.1,0.2,0.85,0.75])
	p.errorbar(wl,flObs,yerr = flObsErr,label= "z="+str(redshift)+", "+str(Lmin) +"< log(L"+line+")<"+ str(Lmax), marker = 'x', c='b', ls='None')
	p.plot(wl_fir, fl_fir,'k',lw=2,label = "SPM E(B-V)="+str(n.round(hdus[2].header['EBV'],3)))
	p.axvline(4861,color='k', ls='dashed')
	p.axvline(4341,color='k', ls='dashed')
	try :
		aa=str(n.round(hdus[0].header['H1_4862_flux_nc']/hdus[0].header['H1_4341_flux_nc'] , 3))
		bb=str(n.round(hdus[0].header['EBV_4862_4341'],3))
		p.text(4331+50,1e-17,r"GP. H$\beta/\gamma$="+aa+", EBV=" +n.round(bb,3))
	except KeyError:
		pass

	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	p.yscale('log')
	p.xlim(( 4331, 4871 ))
	p.legend(fontsize=12, loc=4) 
	p.savefig( outputFigureNameRoot + "-H1lineDecr.png")
	p.clf()

	# full spec line fits
	a0_1 = hdus[5].data['O2_3728_a0a']
	a0_2 = hdus[5].data['O2_3728_a0b']
	continu= hdus[5].data['O2_3728_continu']
	aas =n.arange(hdus[5].data['O2_3728_a0a']-25, hdus[5].data['O2_3728_a0b']+25,0.05)
	flMod=lambda aa,sigma,F0,sh :continu+ gaussianLineNC(aa,sigma,(1-sh)*F0,a0_1)+gaussianLineNC(aa,sigma,sh*F0,a0_2)
	model = flMod(aas, hdus[5].data['O2_3728_sigma'], hdus[5].data['O2_3728_flux'], hdus[5].data['O2_3728_share'] )		
	#print continu, hdus[5].data['O2_3728_flux']
	if continu>=0 and hdus[5].data['O2_3728_flux']>=0 :
		p.figure(2,(4,4))
		p.axes([0.21,0.2,0.78,0.7])
		p.errorbar(wl,flObs,yerr = flObsErr, marker = 'x', c='b', ls='None')
		p.plot(aas, model,'k',label='model', lw=2)
		p.xlabel('wavelength [A]')
		p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
		p.yscale('log')
		p.ylim((model.min()/5., model.max()*5.))
		p.xlim(( hdus[5].data['O2_3728_a0a']-25, hdus[5].data['O2_3728_a0b']+25))
		gl = p.legend(loc=0,fontsize=12)
		gl.set_frame_on(False)
		p.title('[OII] 3727')
		p.savefig( outputFigureNameRoot + "-fs_O2_3728.png")
		p.clf()

	a0 = hdus[5].data['O3_5007_a0']
	continu= hdus[5].data['O3_5007_continu']
	aas =n.arange(hdus[5].data['O3_5007_a0']-25, hdus[5].data['O3_5007_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[5].data['O3_5007_sigma'], hdus[5].data['O3_5007_flux'])
	#print continu, hdus[5].data['O3_5007_flux']
	if continu>=0 and hdus[5].data['O3_5007_flux']>=0 :
		p.figure(2,(4,4))
		p.axes([0.21,0.2,0.78,0.7])
		p.errorbar(wl,flObs,yerr = flObsErr, marker = 'x', c='b', ls='None')
		p.plot(aas, model,'k',label='model', lw =2)
		p.xlabel('wavelength [A]')
		p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
		p.yscale('log')
		p.ylim((model.min()/5., model.max()*5.))
		p.xlim(( hdus[5].data['O3_5007_a0']-25, hdus[5].data['O3_5007_a0']+25))
		gl = p.legend(loc=0,fontsize=12)
		gl.set_frame_on(False)
		p.title('[OIII] 5007')
		p.savefig( outputFigureNameRoot + "-fs_O3_5007.png")
		p.clf()

	a0 = hdus[5].data['H1_4862_a0']
	continu= hdus[5].data['H1_4862_continu']
	aas =n.arange(hdus[5].data['H1_4862_a0']-25, hdus[5].data['H1_4862_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[5].data['H1_4862_sigma'], hdus[5].data['H1_4862_flux'])
	
	#print continu, hdus[5].data['H1_4862_flux']
	if continu>=0 and hdus[5].data['H1_4862_flux']>=0 :
		p.figure(2,(4,4))
		p.axes([0.21,0.2,0.78,0.7])
		p.errorbar(wl,flObs,yerr = flObsErr, marker = 'x', c='b', ls='None')
		p.plot(aas, model,'k',label='model', lw =2)
		p.xlabel('wavelength [A]')
		p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
		p.yscale('log')
		p.ylim((model.min()/5., model.max()*5.))
		p.xlim(( hdus[5].data['H1_4862_a0']-25, hdus[5].data['H1_4862_a0']+25))
		gl = p.legend(loc=0,fontsize=12)
		gl.set_frame_on(False)
		p.title(r'H$\beta$')
		p.savefig( outputFigureNameRoot + "-fs_H1_4862.png")
		p.clf()

	# line spec line fits
	a0_1 = hdus[4].data['O2_3728_a0a']
	a0_2 = hdus[4].data['O2_3728_a0b']
	continu= hdus[4].data['O2_3728_continu']
	aas =n.arange(hdus[4].data['O2_3728_a0a']-25, hdus[4].data['O2_3728_a0b']+25,0.05)
	flMod=lambda aa,sigma,F0,sh :continu+ gaussianLineNC(aa,sigma,(1-sh)*F0,a0_1)+gaussianLineNC(aa,sigma,sh*F0,a0_2)
	model = flMod(aas, hdus[4].data['O2_3728_sigma'], hdus[4].data['O2_3728_flux'], hdus[4].data['O2_3728_share'] )
	#print continu, hdus[4].data['O2_3728_flux']
	if continu>=0 and hdus[4].data['O2_3728_flux']>=0 :
		p.figure(2,(4,4))
		p.axes([0.21,0.2,0.78,0.7])
		p.errorbar(wl_ls, flObs_ls, yerr = flObsErr_ls, marker = 'x', c='b', ls='None')
		p.plot(aas, model,'k',label='model', lw=2)
		p.xlabel('wavelength [A]')
		p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
		p.yscale('log')
		p.ylim((model.min()/5., model.max()*5.))
		p.xlim(( hdus[4].data['O2_3728_a0a']-25, hdus[4].data['O2_3728_a0b']+25))
		gl = p.legend(loc=0,fontsize=12)
		gl.set_frame_on(False)
		p.title('[OII] 3727')
		p.savefig( outputFigureNameRoot + "-ls_O2_3728.png")
		p.clf()

	a0 = hdus[4].data['O3_5007_a0']
	continu= hdus[4].data['O3_5007_continu']
	aas =n.arange(hdus[4].data['O3_5007_a0']-25, hdus[4].data['O3_5007_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[4].data['O3_5007_sigma'], hdus[4].data['O3_5007_flux'])
	#print continu, hdus[4].data['O3_5007_flux']
	if continu>=0 and hdus[4].data['O3_5007_flux']>=0 :
		p.figure(2,(4,4))
		p.axes([0.21,0.2,0.78,0.7])
		p.errorbar(wl_ls, flObs_ls, yerr = flObsErr_ls, marker = 'x', c='b', ls='None')
		p.plot(aas, model,'k',label='model', lw =2)
		p.xlabel('wavelength [A]')
		p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
		p.yscale('log')
		p.ylim((model.min()/5., model.max()*5.))
		p.xlim(( hdus[4].data['O3_5007_a0']-25, hdus[4].data['O3_5007_a0']+25))
		gl = p.legend(loc=0,fontsize=12)
		gl.set_frame_on(False)
		p.title('[OIII] 5007')
		p.savefig( outputFigureNameRoot + "-ls_O3_5007.png")
		p.clf()

	a0 = hdus[4].data['H1_4862_a0']
	continu= hdus[4].data['H1_4862_continu']
	aas =n.arange(hdus[4].data['H1_4862_a0']-25, hdus[4].data['H1_4862_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[4].data['H1_4862_sigma'], hdus[4].data['H1_4862_flux'])
	#print continu, hdus[4].data['H1_4862_flux']
	#if continu>=0 and hdus[4].data['H1_4862_flux']>=0 :
	p.figure(2,(4,4))
	p.axes([0.21,0.2,0.78,0.7])
	p.errorbar(wl_ls, flObs_ls, yerr = flObsErr_ls, marker = 'x', c='b', ls='None')
	p.plot(aas, model,'k',label='model', lw =2)
	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	#p.yscale('log')
	#p.ylim((model.min()/5., model.max()*5.))
	p.ylim((1e-20, 1e-17))
	p.xlim(( hdus[4].data['H1_4862_a0']-25, hdus[4].data['H1_4862_a0']+25))
	gl = p.legend(loc=0,fontsize=12)
	gl.set_frame_on(False)
	p.title(r'H$\beta$')
	p.savefig( outputFigureNameRoot + "-ls_H1_4862.png")
	p.clf()

	a0 = hdus[4].data['H1_4341_a0']
	continu= hdus[4].data['H1_4341_continu']
	aas =n.arange(hdus[4].data['H1_4341_a0']-25, hdus[4].data['H1_4341_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[4].data['H1_4341_sigma'], hdus[4].data['H1_4341_flux'])
	#print continu, hdus[4].data['H1_4341_flux']
	#if continu>=0 and hdus[4].data['H1_4341_flux']>=0 :
	p.figure(2,(4,4))
	p.axes([0.21,0.2,0.78,0.7])
	p.errorbar(wl_ls, flObs_ls, yerr = flObsErr_ls, marker = 'x', c='b', ls='None')
	p.plot(aas, model,'k',label='model', lw =2)
	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	#p.yscale('log')
	#p.ylim((model.min()/5., model.max()*5.))
	p.ylim((1e-20, 1e-17))
	p.xlim(( hdus[4].data['H1_4341_a0']-25, hdus[4].data['H1_4341_a0']+25))
	gl = p.legend(loc=0,fontsize=12)
	gl.set_frame_on(False)
	p.title(r'H$\gamma$')
	p.savefig( outputFigureNameRoot + "-ls_H1_4341.png")
	p.clf()

	a0 = hdus[4].data['H1_4102_a0']
	continu= hdus[4].data['H1_4102_continu']
	aas =n.arange(hdus[4].data['H1_4102_a0']-25, hdus[4].data['H1_4102_a0']+25,0.05)
	flMod=lambda aa,sigma,F0: gaussianLine(aa,sigma,F0,a0,continu)
	model = flMod(aas, hdus[4].data['H1_4102_sigma'], hdus[4].data['H1_4102_flux'])
	#print continu, hdus[4].data['H1_4102_flux']
	#if continu>=0 and hdus[4].data['H1_4102_flux']>=0 :
	p.figure(2,(4,4))
	p.axes([0.21,0.2,0.78,0.7])
	p.errorbar(wl_ls, flObs_ls, yerr = flObsErr_ls, marker = 'x', c='b', ls='None')
	p.plot(aas, model,'k',label='model', lw =2)
	p.xlabel('wavelength [A]')
	p.ylabel(r'f$_\lambda$ [erg cm$^{-2}$ s$^{-1}$ A$^{-1}$]')
	#p.yscale('log')
	#p.ylim((model.min()/5., model.max()*5.))
	p.ylim((1e-20, 1e-17))
	p.xlim(( hdus[4].data['H1_4102_a0']-25, hdus[4].data['H1_4102_a0']+25))
	gl = p.legend(loc=0,fontsize=12)
	gl.set_frame_on(False)
	p.title(r'H$\delta$'+str(hdus[4].data['H1_4102_flux'])+" " + str(hdus[4].data['H1_4102_fluxErr']))
	p.savefig( outputFigureNameRoot + "-ls_H1_4102.png")
	p.clf()
	return hdus


for el in stL[-1:] :
	print "plots ", el
	hdus = plotStack(el)

